name: Docker build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t sudoku .
      # push package to github
      - name: tag
        run: docker tag sudoku med-ridha/sudoku
      - name: Push to Docker Hub
        run: docker push med-ridha/sudoku

