name: Docker build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t sudoku .
      # push package to github
      - name: docker - login
        id: docker_login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: medridhazemzem
          password: ${{ secrets.TOKEN }}

      - name: tag
        run: docker tag sudoku medridhazemzem/sudoku:latest
      - name: Push to Docker Hub
        run: docker push medridhazemzem/sudoku:latest

